pendown
left 90
if(:x > 90 && :y < 100)[
    left 30
    forward 20
]
if(:x > -90 && :y > 100)[
    forward 10
    right 49
    forward 23
]
if(:x < 290 && :y < -100)[
    forward 20
    left 34
    forward 43
]
if(:x >= -90 && :y <= -100)[
    forward 20
    right 30
    forward 34
]

if(:x < 230 && :y > 130)[
    left 60
    forward 20
]
if(:x < -130 && :y < 100)[
    forward 40
    right 49
    forward 23
]
if(:x < 110 && :y < -323)[
    forward 50
    left 34
    forward 43
]
if(:x >= -98 && :y <= -102)[
    forward 50
    right 30
    forward 34
]